language: go
sudo: required
install: true
dist: xenial
go:
  - 1.8.x
  - master
#env:
#  global:
#    - GOARCH=amd64
#    - GO_FOR_RELEASE=1.8
#    - IMAGE_NAME=tsuru/api
services:
  - docker
addons:
  apt:
    packages:
      - postgresql-client
#before_script:
#  - rsyslogd &
#  - sleep 1
before_install:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - go get -u github.com/golang/dep/...
  - cd $TRAVIS_BUILD_DIR
  - sudo wget -O /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/1.14.0/docker-compose-`uname -s`-`uname -m`
  - sudo chmod +x /usr/local/bin/docker-compose
  - cd Docker && ./docker_build.sh && docker-compose up -d
  - cd ..
script:
  - go vet
  - go test -cover
  - go test ./db/models/sqlboiler_models/public/ -c config/databrary_dev.toml
  - go test ./db/models/sqlboiler_models/audit/ -c config/databrary_dev.toml
  - go build .
#after_success:
#  - curl https://raw.githubusercontent.com/tsuru/push-to-docker/master/push.sh | bash
#  - git clean -dfx
#  - test -n "$TRAVIS_TAG" && curl -sL https://raw.githubusercontent.com/tsuru/push-to-packagecloud/master/push.sh | PACKAGE_NAME=tsuru-server bash
#notifications:
#  email:
#    on_success: change
#    on_failure: always
#  slack:
#    secure: QJe4k18ACRUP4CDo245vBFu1hpVlcR3JPWjT7NL/vAE/Y5KDn5pNXIREPYIx9F/f8lvjF2RrQxjApeUujRh1PPt2Q53JulvaDCfM5a5SYnk5yoqu3ynlfqU4AOTDa6kzoJ3K4M9X8JhMpOtr3+IOPbwV88FjPvwviZN4p0L/0wc=
#services:
#  - redis
#  - docker
#  - mongodb
#matrix:
#  allow_failures:
#    - go: master