[log]
path = "/tmp/databrary_log"
level = "DEBUG" #PANIC FATAL ERROR WARN INFO DEBUB

[database]
addr = "localhost"
db_name = "postgres"
port = "5432"
user = "postgres"
pw = "mysecretpassword"
schema = "/home/maksim/dev_projects/go/src/github.com/databrary/databrary/db/schema/master_sql"

